name: Cargo Build & Test

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: JWKS Plugin Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
#          - beta
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy
      - run:  rustup component add rustfmt
      - run: cargo clippy
      - run: cargo build --verbose
      - run: cargo test --verbose
